{{- if and .Values.s3.enabled (not .Values.s3.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flinkui.s3SecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flinkui.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.s3.accessKey | quote }}
  secret-key: {{ .Values.s3.secretKey | quote }}
{{- end }}
